CC=g++ 

LIBS=
LIBS_INC=.

TSK=lz_dispatcher.tsk
SRC=lz_process.cc lz_roundrobin.cc lz_dispatcher.cc lz_dispatcher.t.cc

PTHREAD_ENABLED=#-pthread

CPPFLAGS=$(LIBS_INC:%=-I%) $(LIBS:%=-L%) -g -std=c++11 $(PTHREAD_ENABLED)

all:
	$(CC) $(CPPFLAGS) -o $(TSK) $(SRC)

clean:
	rm -f *.o $(TSK)
